---
- name: update and upgrade packages
  apt:
    update_cache: yes
    upgrade: yes

- name: install dependencies
  apt:
    name:
      - libffi-dev
      - libssl-dev
      - python3-dev
      - python3
      - python3-pip

- name: install docker-compose through pip
  pip:
    name: docker-compose==1.29.2
