---
- name: remove Debian banner which is printed upon login
  file:
    state: absent
    path: /etc/motd

- name: disable SSH password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication yes$'
    line: 'PasswordAuthentication no'
  register: sshd_config

- name: restart SSH daemon
  systemd:
    name: ssh
    state: restarted
  when: sshd_config.changed
