---
- name: remove Debian banner which is printed upon login
  file:
    state: absent
    path: /etc/motd

- name: disable SSH password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: 'PasswordAuthentication yes'
    line: 'PasswordAuthentication no'
  notify: restart ssh.service
